### ISSUE TITLE
Set Card Number

### ISSUE THREAD

**Issue by mahdiapple** [vodvud/php_zklib#12]
Hi.
I change Scripts for set Card Number for user:
ZKlib.php
`    public function setUser($uid, $userid, $name, $password, $role = Util::LEVEL_USER,$card)
    {
        return (new ZK\User())->set($this, $uid, $userid, $name , $password, $role,$card);
    }`

User.php
`    public function set(ZKLib $self, $uid, $userid, $name, $password, $role = Util::LEVEL_USER ,$card)
    {
		
        $self->_section = __METHOD__;

        if (
            (int)$uid === 0 ||
            (int)$uid > Util::USHRT_MAX ||
            strlen($userid) > 9 ||
            strlen($name) > 24 ||
            strlen($password) > 8
        ) {
            return false;
        }

        $command = Util::CMD_SET_USER;
		//echo $command;
        $byte1 = chr((int)($uid % 256));
        $byte2 = chr((int)($uid >> 8));
        $command_string = implode('', [
            $byte1,
            $byte2,
            chr($role),		
            str_pad($password, 8, chr(0)),
            str_pad($name, 24, chr(0)),
			str_pad($card, 13, chr(0)),	
            //str_pad(chr(1), 9, chr(0)),
            str_pad($userid, 8, chr(0)),
            str_repeat(chr(0), 16)
        ]);
print_r($command_string);
        return $self->_command($command, $command_string);
    }`

example.php:
`$zk->setUser(60, '60', 'name', '12345', ZK\Util::LEVEL_ADMIN,12345678);`

But set another number after set
card number:123456
card number after set :0875770417

**Comment by vodvud** [comment]
Hello!
This issue still not solved. See the #2

**Comment by vodvud** [comment]
Fixed in commit e277b4bbe3bc93d11d2aacb773bf188770d78fd8

**Comment by vodvud** [comment]
@mornsina Maybe it depends model?
For model U260-C it works properly.

**Comment by mahdiapple** [comment]
> I have solved this issue. Check this url.
> 
> https://stackoverflow.com/questions/55023178/zkteco-rfid-id-reader-through-php-zklibrary?noredirect=1#comment102231828_55023178

Hi!
So thank you. It is working for me in ZK TFT and Iface models but in Black&White models (tf1700) not working.

**Comment by vodvud** [comment]
Thanks all for check on different devices, this issue closed.
If will have any question please open new one.
