### ISSUE TITLE
Machine Date and Time Error

### ISSUE THREAD

**Issue by aice09** [vodvud/php_zklib#16]
After getting user attendance data form the machine, the date and time of the biometrics machine change. How to fix the issue?

**Comment by vodvud** [comment]
Hi!
Maybe you used method `setTime`?

https://github.com/vodvud/php_zklib/blob/4602482cbdf018665e03b82dc59134eaac440cb0/example.php#L21

https://github.com/vodvud/php_zklib/blob/4602482cbdf018665e03b82dc59134eaac440cb0/zklib/src/Time.php#L9-L22

Because only this one can update time at the machine.

**Comment by aice09** [comment]
Thank you, my bad! Working very well!
I also add the default timezone before setting the time.
`date_default_timezone_set('Asia/Manila'); //Default Timezone`
`$zk->setTime(date('Y-m-d H:i:s'));`
