### ISSUE TITLE
How can I add user?

### ISSUE THREAD

**Issue by maodahua** [vodvud/php_zklib#4]
Hi there!
I use a setUser function but I can not add user, could you please tell me how to add user.

**Comment by maodahua** [comment]
eeeeem.....
Hi!
I retry it WORK! and it is my bad. I ignore $uid max is 2^16.
thanks a lot!
I am a starter of php and zk devices. but I must use php to build a website, get users fingerprint return value is annoy me.
so , could you please give me a example? how to get the fingerprint and show the fingerprint.
thank again!

**Comment by vodvud** [comment]
Sorry, but [Fingerprint](php_zklib/zklib/src/Fingerprint.php) still uncompleted. 
I need more documentation about it, or play with data and try.

**Comment by maodahua** [comment]
OK, thanks .
step up efforts!
