### ISSUE TITLE
How to insert all data record to database

### ISSUE THREAD

**Issue by yudisdwi26** [vodvud/php_zklib#8]
I was try to download and receive all record and its work when its code are echo, but not to insert into database.. can you help me ?

**Comment by yudisdwi26** [comment]
![1](https://user-images.githubusercontent.com/38997504/54729335-8986fe00-4bb5-11e9-9494-08806367058b.jpg)

**Comment by yudisdwi26** [comment]
![1](https://user-images.githubusercontent.com/38997504/54729361-b804d900-4bb5-11e9-88e7-3e3c2f4a9e34.jpg)

**Comment by vodvud** [comment]
Hi @yudisdwi26 
I see error in your code, remove the row
`foreach ($users as $uItem) {`
above the row
`foreach ($attendance as $attItem) {`

**Comment by yudisdwi26** [comment]
![filter](https://user-images.githubusercontent.com/38997504/54865823-23110400-4d9e-11e9-8630-0f6cbe91ce8c.png)

how to filter sign when 8.00 AM is sign in and 5.00 pm sign out.. ? please help sir.. thanks

**Comment by vodvud** [comment]
@yudisdwi26 Sorry, but this is question not about this library. 
Please use google for that next time!

Example for your situation
```sql
DATEPART(hour, `sign`) BETWEEN 8 AND 17
```

**Comment by yudisdwi26** [comment]
sorry that's not what i meant ... can when downloading data record. one date but two times one as sign in and one as sign out.. 
`$Date = date("Y-m-d", strtotime($attItem['timestamp']));
$Sign_in = date("H:i:s", strtotime($attItem['timestamp']));`

output : 
as example : 
1 | Didi | 2019/03/25 | 08:00:00
1 | Didi | 2019/03/25 | 17:00:00

but can you help me to make format : 
1 | Didi | 2019/03/25 | 08:00:00 | 17:00:00.

Im sory talking to you again. because i have use google and many source code but not working..

**Comment by vodvud** [comment]
@yudisdwi26 Hi!
You have answer into your question.

create a table `attendance` with structure like this
`id | uid | date | time_in | time_out`

Then do select by date before insert or update
```sql
SELECT `id` FROM `attendance` WHERE `date`=:date;
```

if select returned `id` do update `time_out`
```sql
UPDATE `attendance` SET `time_out`=:time WHERE `id`=:id;
```

else insert without `time_out`
```sql
INSERT INTO `attendance` (`uid`, `date`, `time_in`, `time_out`) VALUES (:uid, :date, :time, '00:00:00');
```

Will be one row per day like you want.

**Comment by yudisdwi26** [comment]
Thanks you for your attention..
![ask](https://user-images.githubusercontent.com/38997504/55218691-5f78b000-5235-11e9-8b2d-ead001996cf7.png)
last my question sir, can you help to make its when i search data only one day record or only one date

**Comment by yudisdwi26** [comment]
![ask](https://user-images.githubusercontent.com/38997504/55218850-de6de880-5235-11e9-8e3b-8eba74e7da7c.png)

**Comment by yudisdwi26** [comment]
![ask](https://user-images.githubusercontent.com/38997504/55218897-fa718a00-5235-11e9-9916-c78cde209c4d.png)

**Comment by vodvud** [comment]
Hi @yudisdwi26

You did some mistake in your code, because should not be more then one row per day.
Please review your code and fix by yourself.

Thank you!

**Comment by yudisdwi26** [comment]
is there primary key or index in table field ? and in realtime someone ussually do more than one finger in time... therefore make it more than one row per day... big thanks for your answer...

**Comment by vodvud** [comment]
`id` is primary key, auto increment. But if you don't like to use it, you can update by `date` field.

**Comment by yudisdwi26** [comment]
Hi!
i was try to review my code from you.. in a realtime someone can be finger more than one and it makes record twice.. im really hope you can help to solve this...
![1](https://user-images.githubusercontent.com/38997504/55391131-efcf3180-5562-11e9-9c82-13c0e61493d0.png)
Sory I type in bahasa.. tanggal is date, and absensi is attendance..
Thanks bro!

**Comment by yudisdwi26** [comment]
when i try to unique for date.. its work for one day one row but other ID is nor inserted..

**Comment by dalersingh** [comment]
@yudisdwi26 This issue is not related to ZK library code, there are logical problems in your coding, which are very basic.  Unfortunately, we try our best to answer or support questions related to ZK library here. It would not be possible for us to fix or explain basic programming logic. 

May be you can work a bit more on your logical design or take in-person help from someone senior around you in relation to this issue.

I hope you understand
